<?php

namespace Database\Seeders;

use App\Models\Feature;
use App\Models\Plan;
use Illuminate\Database\Seeder;

class PlansAndFeaturesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $features = [
            ['name' => 'Project Management', 'code' => 'project.management', 'module' => 'projects', 'version_introduced' => '1.0'],
            ['name' => 'BOQ Management', 'code' => 'boq.management', 'module' => 'boq', 'version_introduced' => '1.0'],
            ['name' => 'Excel Import', 'code' => 'boq.import.excel', 'module' => 'boq', 'version_introduced' => '1.0'],
            ['name' => 'PDF Import', 'code' => 'boq.import.pdf', 'module' => 'boq', 'version_introduced' => '1.0', 'requires_topup' => true],
            ['name' => 'OCR Scanning', 'code' => 'ocr.scanning', 'module' => 'ai', 'version_introduced' => '1.0', 'requires_topup' => true],
            ['name' => 'AI BOQ Extraction', 'code' => 'ai.boq.extraction', 'module' => 'ai', 'version_introduced' => '1.0', 'requires_topup' => true],
            ['name' => 'AI Pricing', 'code' => 'ai.pricing.analysis', 'module' => 'ai', 'version_introduced' => '1.0', 'requires_topup' => true],
            ['name' => 'Rate Library', 'code' => 'rate.library', 'module' => 'rates', 'version_introduced' => '1.0'],
            ['name' => 'Supplier Management', 'code' => 'supplier.management', 'module' => 'suppliers', 'version_introduced' => '1.0'],
            ['name' => 'Variations', 'code' => 'variations', 'module' => 'projects', 'version_introduced' => '2.0', 'requires_topup' => true],
            ['name' => 'Interim Payment Certificates', 'code' => 'payment.certificates', 'module' => 'projects', 'version_introduced' => '3.0', 'requires_topup' => true],
            ['name' => 'Actual Cost Tracking', 'code' => 'cost.tracking', 'module' => 'projects', 'version_introduced' => '2.0', 'requires_topup' => true],
            ['name' => 'Advanced Reports', 'code' => 'reports.advanced', 'module' => 'reports', 'version_introduced' => '1.0'],
            ['name' => 'PDF Export', 'code' => 'export.pdf', 'module' => 'reports', 'version_introduced' => '1.0'],
            ['name' => 'Excel Export', 'code' => 'export.excel', 'module' => 'reports', 'version_introduced' => '1.0'],
            ['name' => 'Flutter Mobile Access', 'code' => 'mobile.access', 'module' => 'mobile', 'version_introduced' => '1.0'],
            ['name' => 'Offline Mode', 'code' => 'offline.mode', 'module' => 'mobile', 'version_introduced' => '1.0'],
            ['name' => 'Multilingual Support', 'code' => 'multilingual', 'module' => 'settings', 'version_introduced' => '1.0'],
            ['name' => 'Translation Management', 'code' => 'translation.management', 'module' => 'translations', 'version_introduced' => '1.0'],
            ['name' => 'Advanced Analytics', 'code' => 'analytics.advanced', 'module' => 'reports', 'version_introduced' => '2.0', 'requires_topup' => true],
            ['name' => 'API Access', 'code' => 'api.access', 'module' => 'api', 'version_introduced' => '1.0'],
            ['name' => 'Team Collaboration', 'code' => 'team.collaboration', 'module' => 'organisations', 'version_introduced' => '1.0'],
            ['name' => 'Document Storage', 'code' => 'document.storage', 'module' => 'documents', 'version_introduced' => '1.0'],
            ['name' => 'Feature Updates', 'code' => 'feature.updates', 'module' => 'updates', 'version_introduced' => '1.0'],
        ];

        foreach ($features as $feature) {
            Feature::updateOrCreate(['code' => $feature['code']], $feature);
        }

        $plans = [
            [
                'name' => 'Free Trial',
                'code' => 'free-trial',
                'description' => 'Free trial access to core features.',
                'type' => 'monthly',
                'duration_days' => 14,
                'price' => 0,
                'currency' => 'UGX',
                'has_trial' => true,
                'trial_days' => 14,
                'max_projects' => 1,
                'max_boqs' => 2,
                'max_ai_credits' => 10,
                'max_ocr_pages' => 10,
                'max_translations' => 50,
                'feature_update_eligible' => false,
                'display_order' => 1,
                'features' => [
                    'project.management',
                    'boq.management',
                    'boq.import.excel',
                    'rate.library',
                    'export.pdf',
                    'export.excel',
                    'multilingual',
                ],
            ],
            [
                'name' => 'One-Time Access',
                'code' => 'one-time',
                'description' => 'One-time access to the current product version.',
                'type' => 'one_time',
                'duration_days' => 365,
                'price' => 150000,
                'currency' => 'UGX',
                'max_projects' => 5,
                'max_boqs' => 10,
                'max_ai_credits' => 100,
                'max_ocr_pages' => 100,
                'max_translations' => 500,
                'feature_update_eligible' => true,
                'display_order' => 2,
                'features' => [
                    'project.management',
                    'boq.management',
                    'boq.import.excel',
                    'boq.import.pdf',
                    'rate.library',
                    'supplier.management',
                    'reports.advanced',
                    'export.pdf',
                    'export.excel',
                    'mobile.access',
                    'offline.mode',
                    'multilingual',
                    'translation.management',
                    'api.access',
                    'team.collaboration',
                    'document.storage',
                    'feature.updates',
                ],
            ],
            [
                'name' => 'Monthly Professional',
                'code' => 'monthly-professional',
                'description' => 'Monthly subscription for professionals.',
                'type' => 'monthly',
                'duration_days' => 30,
                'price' => 50000,
                'currency' => 'UGX',
                'auto_renewal' => true,
                'grace_period_days' => 7,
                'max_projects' => 10,
                'max_boqs' => 20,
                'max_ai_credits' => 200,
                'max_ocr_pages' => 200,
                'max_translations' => 1000,
                'feature_update_eligible' => true,
                'display_order' => 3,
                'features' => [
                    'project.management',
                    'boq.management',
                    'boq.import.excel',
                    'boq.import.pdf',
                    'ocr.scanning',
                    'ai.boq.extraction',
                    'ai.pricing.analysis',
                    'rate.library',
                    'supplier.management',
                    'reports.advanced',
                    'export.pdf',
                    'export.excel',
                    'mobile.access',
                    'offline.mode',
                    'multilingual',
                    'translation.management',
                    'api.access',
                    'team.collaboration',
                    'document.storage',
                    'feature.updates',
                ],
            ],
            [
                'name' => 'Three-Month Professional',
                'code' => 'three-month-professional',
                'description' => 'Three-month subscription for professionals.',
                'type' => 'three_month',
                'duration_days' => 90,
                'price' => 135000,
                'currency' => 'UGX',
                'auto_renewal' => true,
                'grace_period_days' => 7,
                'max_projects' => 10,
                'max_boqs' => 20,
                'max_ai_credits' => 600,
                'max_ocr_pages' => 600,
                'max_translations' => 3000,
                'feature_update_eligible' => true,
                'display_order' => 4,
                'features' => [
                    'project.management',
                    'boq.management',
                    'boq.import.excel',
                    'boq.import.pdf',
                    'ocr.scanning',
                    'ai.boq.extraction',
                    'ai.pricing.analysis',
                    'rate.library',
                    'supplier.management',
                    'reports.advanced',
                    'export.pdf',
                    'export.excel',
                    'mobile.access',
                    'offline.mode',
                    'multilingual',
                    'translation.management',
                    'api.access',
                    'team.collaboration',
                    'document.storage',
                    'feature.updates',
                ],
            ],
            [
                'name' => 'Six-Month Professional',
                'code' => 'six-month-professional',
                'description' => 'Six-month subscription for professionals.',
                'type' => 'six_month',
                'duration_days' => 180,
                'price' => 240000,
                'currency' => 'UGX',
                'auto_renewal' => true,
                'grace_period_days' => 7,
                'max_projects' => 10,
                'max_boqs' => 20,
                'max_ai_credits' => 1200,
                'max_ocr_pages' => 1200,
                'max_translations' => 6000,
                'feature_update_eligible' => true,
                'display_order' => 5,
                'features' => [
                    'project.management',
                    'boq.management',
                    'boq.import.excel',
                    'boq.import.pdf',
                    'ocr.scanning',
                    'ai.boq.extraction',
                    'ai.pricing.analysis',
                    'rate.library',
                    'supplier.management',
                    'reports.advanced',
                    'export.pdf',
                    'export.excel',
                    'mobile.access',
                    'offline.mode',
                    'multilingual',
                    'translation.management',
                    'api.access',
                    'team.collaboration',
                    'document.storage',
                    'feature.updates',
                ],
            ],
            [
                'name' => 'Annual Professional',
                'code' => 'annual-professional',
                'description' => 'Annual subscription for professionals.',
                'type' => 'annual',
                'duration_days' => 365,
                'price' => 450000,
                'currency' => 'UGX',
                'auto_renewal' => true,
                'grace_period_days' => 14,
                'max_projects' => 10,
                'max_boqs' => 20,
                'max_ai_credits' => 2400,
                'max_ocr_pages' => 2400,
                'max_translations' => 12000,
                'feature_update_eligible' => true,
                'display_order' => 6,
                'features' => [
                    'project.management',
                    'boq.management',
                    'boq.import.excel',
                    'boq.import.pdf',
                    'ocr.scanning',
                    'ai.boq.extraction',
                    'ai.pricing.analysis',
                    'rate.library',
                    'supplier.management',
                    'reports.advanced',
                    'export.pdf',
                    'export.excel',
                    'mobile.access',
                    'offline.mode',
                    'multilingual',
                    'translation.management',
                    'api.access',
                    'team.collaboration',
                    'document.storage',
                    'feature.updates',
                ],
            ],
            [
                'name' => 'Lifetime Access',
                'code' => 'lifetime',
                'description' => 'Lifetime access to the current product version.',
                'type' => 'lifetime',
                'duration_days' => null,
                'price' => 1500000,
                'currency' => 'UGX',
                'max_projects' => 50,
                'max_boqs' => 100,
                'max_ai_credits' => 5000,
                'max_ocr_pages' => 5000,
                'max_translations' => 25000,
                'feature_update_eligible' => true,
                'display_order' => 7,
                'features' => [
                    'project.management',
                    'boq.management',
                    'boq.import.excel',
                    'boq.import.pdf',
                    'ocr.scanning',
                    'ai.boq.extraction',
                    'ai.pricing.analysis',
                    'rate.library',
                    'supplier.management',
                    'reports.advanced',
                    'export.pdf',
                    'export.excel',
                    'mobile.access',
                    'offline.mode',
                    'multilingual',
                    'translation.management',
                    'api.access',
                    'team.collaboration',
                    'document.storage',
                    'feature.updates',
                ],
            ],
        ];

        foreach ($plans as $planData) {
            $featureCodes = $planData['features'];
            unset($planData['features']);

            $plan = Plan::updateOrCreate(['code' => $planData['code']], $planData);

            $plan->features()->sync(
                Feature::whereIn('code', $featureCodes)->pluck('id')
            );
        }
    }
}
