<div class="min-h-screen bg-slate-50"><div class="max-w-7xl mx-auto p-6">
<div class="flex flex-wrap items-center justify-between gap-3 mb-6"><div><h1 class="text-2xl font-bold text-slate-900">Subscription Plans</h1><p class="text-slate-500">Create and manage plan pricing, limits and trial eligibility.</p></div><button wire:click="create" class="px-4 py-2 rounded-lg bg-indigo-600 text-white">Add Plan</button></div>
@if(session('message'))<div class="mb-4 p-3 rounded-lg bg-emerald-50 text-emerald-700">{{ session('message') }}</div>@endif
@if($showForm)<div class="bg-white border rounded-2xl p-5 mb-6 shadow-sm"><form wire:submit="save" class="grid grid-cols-1 md:grid-cols-3 gap-4">
<div><label class="text-sm">Name</label><input wire:model="form.name" class="mt-1 w-full rounded-lg border-slate-300"></div>
<div><label class="text-sm">Code</label><input wire:model="form.code" class="mt-1 w-full rounded-lg border-slate-300" placeholder="auto-generated if empty"></div>
<div><label class="text-sm">Type</label><select wire:model="form.type" class="mt-1 w-full rounded-lg border-slate-300"><option value="monthly">Monthly</option><option value="three_month">3 Months</option><option value="six_month">6 Months</option><option value="annual">Annual</option><option value="one_time">One Time</option><option value="lifetime">Lifetime</option></select></div>
<div class="md:col-span-3"><label class="text-sm">Description</label><textarea wire:model="form.description" class="mt-1 w-full rounded-lg border-slate-300"></textarea></div>
@foreach(['price'=>'Price','currency'=>'Currency','duration_days'=>'Duration Days','max_users'=>'Max Users','max_projects'=>'Max Projects','max_boqs'=>'Max BOQs','max_ai_credits'=>'AI Credits','max_ocr_pages'=>'OCR Pages','max_translations'=>'Translations','grace_period_days'=>'Grace Days','display_order'=>'Display Order'] as $field=>$label)<div><label class="text-sm">{{ $label }}</label><input wire:model="form.{{ $field }}" class="mt-1 w-full rounded-lg border-slate-300" type="{{ $field==='currency' ? 'text' : 'number' }}"></div>@endforeach
<div><label class="text-sm">Storage bytes</label><input wire:model="form.max_storage_bytes" type="number" class="mt-1 w-full rounded-lg border-slate-300"></div>
<div class="flex gap-5 items-center md:col-span-3"><label><input type="checkbox" wire:model="form.is_active"> Active</label><label><input type="checkbox" wire:model="form.has_trial"> Trial enabled</label><label><input type="checkbox" wire:model="form.auto_renewal"> Auto renewal</label><div><label class="text-sm">Trial days</label><input wire:model="form.trial_days" type="number" class="ml-2 w-24 rounded-lg border-slate-300"></div></div>
<div class="md:col-span-3 flex gap-2"><button class="px-4 py-2 bg-indigo-600 text-white rounded-lg">Save</button><button type="button" wire:click="cancel" class="px-4 py-2 border rounded-lg">Cancel</button></div>
</form></div>@endif
<div class="mb-4"><input wire:model.live.debounce.300ms="search" placeholder="Search plans..." class="w-full md:w-96 rounded-lg border-slate-300"></div>
<div class="bg-white border rounded-2xl overflow-x-auto"><table class="min-w-full divide-y"><thead class="bg-slate-50"><tr>@foreach(['Plan','Price','Duration','Limits','Status','Actions'] as $h)<th class="px-4 py-3 text-left text-xs uppercase text-slate-500">{{ $h }}</th>@endforeach</tr></thead><tbody class="divide-y">@forelse($plans as $plan)<tr><td class="px-4 py-3"><div class="font-semibold">{{ $plan->name }}</div><div class="text-xs text-slate-500">{{ $plan->code }}</div></td><td class="px-4 py-3">{{ $plan->currency }} {{ number_format((float)$plan->price,2) }}</td><td class="px-4 py-3">{{ $plan->duration_days ?: '—' }} days</td><td class="px-4 py-3 text-sm">{{ $plan->max_projects ?? '∞' }} projects · {{ $plan->max_boqs ?? '∞' }} BOQs · {{ $plan->max_ai_credits ?? '∞' }} AI</td><td class="px-4 py-3"><span class="px-2 py-1 rounded-full text-xs {{ $plan->is_active ? 'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-600' }}">{{ $plan->is_active?'Active':'Inactive' }}</span></td><td class="px-4 py-3 whitespace-nowrap"><button wire:click="edit({{ $plan->id }})" class="text-indigo-600 mr-3">Edit</button><button wire:click="toggleActive({{ $plan->id }})" class="text-slate-600 mr-3">{{ $plan->is_active?'Deactivate':'Activate' }}</button>@unless($plan->is_archived)<button wire:click="archive({{ $plan->id }})" wire:confirm="Archive this plan? Existing subscriptions will remain." class="text-red-600">Archive</button>@endunless</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">No plans found.</td></tr>@endforelse</tbody></table><div class="p-4">{{ $plans->links() }}</div></div>
</div></div>
