#!/usr/bin/env bash
set -euo pipefail

APP_DIR="${APP_DIR:-$(cd "$(dirname "$0")/.." && pwd)}"
PHP_BIN="${PHP_BIN:-php}"
COMPOSER_BIN="${COMPOSER_BIN:-composer}"
NPM_BIN="${NPM_BIN:-npm}"

cd "$APP_DIR"

echo "[1/8] Checking production environment"
if [[ ! -f .env ]]; then
  echo "ERROR: .env is missing. Copy .env.production.example to .env and configure it first." >&2
  exit 1
fi

if grep -Eq '^APP_DEBUG=(true|1)$' .env; then
  echo "ERROR: APP_DEBUG must be false in production." >&2
  exit 1
fi

if grep -Eq '^APP_ENV=(local|testing)$' .env; then
  echo "ERROR: APP_ENV must be production." >&2
  exit 1
fi

echo "[2/8] Entering maintenance mode"
$PHP_BIN artisan down --retry=60 || true

restore_app() {
  $PHP_BIN artisan up || true
}
trap restore_app EXIT

echo "[3/8] Installing PHP dependencies"
$COMPOSER_BIN install --no-dev --prefer-dist --optimize-autoloader --no-interaction

echo "[4/8] Building frontend assets"
if command -v "$NPM_BIN" >/dev/null 2>&1; then
  $NPM_BIN ci
  $NPM_BIN run build
else
  echo "WARNING: npm is unavailable. Ensure public/build was generated by CI before deploying." >&2
fi

echo "[5/8] Running database migrations"
$PHP_BIN artisan migrate --force

echo "[6/8] Refreshing Laravel caches"
$PHP_BIN artisan optimize:clear
$PHP_BIN artisan config:cache
$PHP_BIN artisan route:cache
$PHP_BIN artisan view:cache

echo "[7/8] Ensuring storage link"
$PHP_BIN artisan storage:link || true

echo "[8/8] Deployment checks"
$PHP_BIN artisan route:list --path=api/v1 >/dev/null
$PHP_BIN artisan subscriptions:expire || true
$PHP_BIN artisan payments:reconcile --hours=48 || true

restore_app
trap - EXIT

echo "Deployment completed successfully."
